#!/usr/bin/zsh
alias artisan="docker-compose exec php php artisan"
alias composer="docker-compose exec php composer"
alias psql="docker exec -it laravel-pgsql psql -h pgsql -U pguser pgdb"
# source cli/alias
